<a href="https://colab.research.google.com/github/smileone22/20Fall_R-BASIC-learningforBigData/blob/master/2_Numpy_modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Exploring Numpy

- Package for mathematical, scientific computation
- Faster than python lists
- Use less memory than python lists
- Has many useful built_in functions 
- Lists vs Numpy.array? 
    - It is a data structure for storing data
    - Can be multiple dimension
    - For 1-D list: numpy.array([data1, data2, ....])
    - For 2-D list: numpy.array([data1, data2, ....], [data1,data2,data3, ...])
    - called "nd array" (n-dimension_arry)

In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

In [3]:
# Using Alias
import numpy as np

In [4]:
# Creating ndarray
arr=np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [7]:
# list in python
[1,2,3,4]

[1, 2, 3, 4]

In [12]:
#Comparing types
type(arr) , type([1,2,3,4])

(numpy.ndarray, list)

In [13]:
#Creating ndarry from list
list1=[1,2,3,4]
list2=[[1,2,3,4],[5,6,7,8]]
arr1=np.array(list1)
arr2=np.array(list2)

In [14]:
arr1

array([1, 2, 3, 4])

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#Comparing shapes - shapes are really important!
arr1.shape

(4,)

In [19]:
arr2.shape

(2, 4)

In [24]:
# Data types from array
# Different from lists, array allows SIGNLE data type
list1=[1,3.14,"Apple",'1234'] #mix of integer, float, string
arr =np.array([1,2,3,3.14]) # mix of integer and float    
arr #all floats

array([1.  , 2.  , 3.  , 3.14])

In [26]:
# Setting dtype to int when array is comprised of integers and floats 
arr =np.array([1,2,3,3.14],dtype=int)
arr #all ints

array([1, 2, 3, 3])

In [28]:
# When array is a mixture of int and str
arr = np.array([1,3.14,'Apple','1234'])
arr #all string

array(['1', '3.14', 'Apple', '1234'], dtype='<U32')

In [29]:
arr[0]+arr[1] #Becomes string concatenation

'13.14'

In [33]:
arr =np.array([1,2,'Apple',3.14],dtype=int) #Error

ValueError: ignored

In [32]:
arr =np.array([1,2,'1234',3.14],dtype=int) #No error

In [38]:
# Slicing - Selecting parts from array 
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

# Using index
arr[9]

9

In [39]:
arr[-1] # Counts from backwards 

9

In [43]:
# 2D array
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr2d.shape

(3, 4)

In [44]:
arr2d[0,2]

3

In [45]:
arr2d[2,1]

10

In [46]:
# Range 
# one dimensional 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[1:] #index 1 to the end

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[:5] #index less than 5

array([0, 1, 2, 3, 4])

In [52]:
arr [1:5] # from index 1-5 : does not include index5, but the 5th element 

array([1, 2, 3, 4])

In [54]:
# Range 
# 2-dimensional 

arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2d[0,:] # Bring all data from the first row(index=0)

array([1, 2, 3, 4])

In [56]:
# Bring all data from the second column
arr2d[:,2]

array([ 3,  7, 11])

In [57]:
arr2d[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
arr2d[:2,2:]

array([[3, 4],
       [7, 8]])

In [63]:
# Fancy Indexing: Used to select group of indexes not in the order of range  

arr =np.array([10,23,2,7,90,65,32,66,70])
idx= [1,3,5]
arr[idx] # Cool!

array([23,  7, 65])

In [64]:
#2D array 
arr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
arr2d[:,[1,2,3]] #everything except for the first element(index=0) from all arrays

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [67]:
# Boolean Indexing 
# Boolean indexing Through conditional filtering
arr=np.array([1,2,3,4,5,6,7])
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
TrueFalse=[True, False, True]
#arr[TrueFalse] #IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3
TF = [True, False, True,False,True, False, True] # needs same length 
arr[TF]  #TRUE=1,3,5,7/FALSE=2,4,6

array([1, 3, 5, 7])

In [68]:
# Conditional Filtering
arr2d > 0 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
arr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
arr2d [arr2d >2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
arr2d[arr2d <5]

array([1, 2, 3, 4])

In [77]:
# Arange 
arr= [1,2,3,4,5,6,7,8,9,10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [78]:
arr =np.arange(start=1,stop=11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
# Odd numbers between 1 and 10
arr = np.arange(1,11,2)
arr 

array([1, 3, 5, 7, 9])

In [83]:
arr = np.arange(start=1,stop=11,step=2)
arr

array([1, 3, 5, 7, 9])

In [90]:
# Python's range vs Numpy's arange
arr=np.arange(1,11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [89]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [91]:
# Using functions: np.ones , np.zeros
np.ones((4,5)) #Fill 4th row, 5th column with 1s 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [94]:
# Using np.full
np.full((3,4,2),7) #Fill all 3 of 4*2 matrices with 7  

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [95]:
# Using np.linspace 
np.linspace(1,10,3) #(first element,last element, total number of elements with same length)


array([ 1. ,  5.5, 10. ])

In [96]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [97]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [98]:
# If no distance/ number,  default = 50
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [101]:
# Using np.reshape
# Used to alter structure, dimension of the nd array
x= np.arange(1,16)
np.shape(x) 

(15,)

In [102]:
x.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])