<a href="https://colab.research.google.com/github/smileone22/20Fall_R-BASIC-learningforBigData/blob/master/2_Numpy_modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exploring Numpy mostly through np.array()

- Package for mathematical, scientific computation
- Faster than python lists
- Use less memory than python lists
- Has many useful built_in functions 
- Lists vs Numpy.array? 
    - It is a data structure for storing data
    - Can be multiple dimension
    - For 1-D list: numpy.array([data1, data2, ....])
    - For 2-D list: numpy.array([data1, data2, ....], [data1,data2,data3, ...])
    - called "nd array" (n-dimension_arry)

In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

In [3]:
# Using Alias
import numpy as np

In [4]:
# Creating ndarray
arr=np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [7]:
# list in python
[1,2,3,4]

[1, 2, 3, 4]

In [12]:
#Comparing types
type(arr) , type([1,2,3,4])

(numpy.ndarray, list)

In [13]:
#Creating ndarry from list
list1=[1,2,3,4]
list2=[[1,2,3,4],[5,6,7,8]]
arr1=np.array(list1)
arr2=np.array(list2)

In [14]:
arr1

array([1, 2, 3, 4])

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#Comparing shapes - shapes are really important!
arr1.shape

(4,)

In [19]:
arr2.shape

(2, 4)

In [24]:
# Data types from array
# Different from lists, array allows SIGNLE data type
list1=[1,3.14,"Apple",'1234'] #mix of integer, float, string
arr =np.array([1,2,3,3.14]) # mix of integer and float    
arr #all floats

array([1.  , 2.  , 3.  , 3.14])

In [26]:
# Setting dtype to int when array is comprised of integers and floats 
arr =np.array([1,2,3,3.14],dtype=int)
arr #all ints

array([1, 2, 3, 3])

In [28]:
# When array is a mixture of int and str
arr = np.array([1,3.14,'Apple','1234'])
arr #all string

array(['1', '3.14', 'Apple', '1234'], dtype='<U32')

In [29]:
arr[0]+arr[1] #Becomes string concatenation

'13.14'

In [33]:
arr =np.array([1,2,'Apple',3.14],dtype=int) #Error

ValueError: ignored

In [32]:
arr =np.array([1,2,'1234',3.14],dtype=int) #No error

In [38]:
# Slicing - Selecting parts from array 
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

# Using index
arr[9]

9

In [39]:
arr[-1] # Counts from backwards 

9

In [43]:
# 2D array
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr2d.shape

(3, 4)

In [44]:
arr2d[0,2]

3

In [45]:
arr2d[2,1]

10

In [46]:
# Range 
# one dimensional 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[1:] #index 1 to the end

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[:5] #index less than 5

array([0, 1, 2, 3, 4])

In [52]:
arr [1:5] # from index 1-5 : does not include index5, but the 5th element 

array([1, 2, 3, 4])

In [54]:
# Range 
# 2-dimensional 

arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2d[0,:] # Bring all data from the first row(index=0)

array([1, 2, 3, 4])

In [56]:
# Bring all data from the second column
arr2d[:,2]

array([ 3,  7, 11])

In [57]:
arr2d[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
arr2d[:2,2:]

array([[3, 4],
       [7, 8]])

In [63]:
# Fancy Indexing: Used to select group of indexes not in the order of range  

arr =np.array([10,23,2,7,90,65,32,66,70])
idx= [1,3,5]
arr[idx] # Cool!

array([23,  7, 65])

In [64]:
#2D array 
arr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
arr2d[:,[1,2,3]] #everything except for the first element(index=0) from all arrays

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [67]:
# Boolean Indexing 
# Boolean indexing Through conditional filtering
arr=np.array([1,2,3,4,5,6,7])
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
TrueFalse=[True, False, True]
#arr[TrueFalse] #IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3
TF = [True, False, True,False,True, False, True] # needs same length 
arr[TF]  #TRUE=1,3,5,7/FALSE=2,4,6

array([1, 3, 5, 7])

In [68]:
# Conditional Filtering
arr2d > 0 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
arr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
arr2d [arr2d >2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
arr2d[arr2d <5]

array([1, 2, 3, 4])

In [77]:
# Arange 
arr= [1,2,3,4,5,6,7,8,9,10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [78]:
arr =np.arange(start=1,stop=11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
# Odd numbers between 1 and 10
arr = np.arange(1,11,2)
arr 

array([1, 3, 5, 7, 9])

In [83]:
arr = np.arange(start=1,stop=11,step=2)
arr

array([1, 3, 5, 7, 9])

In [90]:
# Python's range vs Numpy's arange
arr=np.arange(1,11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [89]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [91]:
# Using functions: np.ones , np.zeros
np.ones((4,5)) #Fill 4th row, 5th column with 1s 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [94]:
# Using np.full
np.full((3,4,2),7) #Fill all 3 of 4*2 matrices with 7  

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [95]:
# Using np.linspace 
np.linspace(1,10,3) #(first element,last element, total number of elements with same length)


array([ 1. ,  5.5, 10. ])

In [96]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [97]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [98]:
# If no distance/ number,  default = 50
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [101]:
# Using np.reshape
# Used to alter structure, dimension of the nd array
x= np.arange(1,16)
np.shape(x) 

(15,)

In [102]:
x.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
# Using random sub modules to create ndarray
# rand function: rand() - creates random ndarray between 0~10 
np.random.rand(4,5,3)


array([[[0.83673223, 0.94004946, 0.23249194],
        [0.45150303, 0.39970694, 0.26191873],
        [0.37556536, 0.36290439, 0.48194189],
        [0.89295789, 0.35997003, 0.83001173],
        [0.40085047, 0.82770281, 0.87146211]],

       [[0.94825659, 0.10112745, 0.3991409 ],
        [0.86617238, 0.20423567, 0.56122097],
        [0.70615557, 0.91539742, 0.84283539],
        [0.75025207, 0.09638784, 0.90853478],
        [0.1343318 , 0.46289394, 0.73028013]],

       [[0.10403527, 0.19890467, 0.15397382],
        [0.51684283, 0.46439934, 0.89986482],
        [0.18484267, 0.14222411, 0.97443181],
        [0.51044427, 0.10911535, 0.66540664],
        [0.95489979, 0.70518053, 0.73964808]],

       [[0.7787709 , 0.2870408 , 0.29175939],
        [0.6235325 , 0.75412029, 0.95710952],
        [0.23430288, 0.01994789, 0.82636557],
        [0.54454469, 0.78411184, 0.10780243],
        [0.4742284 , 0.46328472, 0.85780142]]])

In [105]:
# randn() : n -> normal distribution 
# Creates random ndarray sampled through normal distribution
np.random.randn(5)

array([0.58401927, 0.31456302, 0.18879254, 2.48193762, 0.86576818])

In [106]:
np.random.randn(4,5,3)

array([[[ 4.54343230e-01,  5.66193336e-01,  1.29997407e+00],
        [ 1.25829668e+00,  1.53982915e-01, -1.15673635e+00],
        [ 3.61698528e-01,  1.14263196e+00, -1.55251016e-01],
        [-1.93207425e+00,  1.32147109e+00, -1.81788158e+00],
        [ 4.21979797e-01, -6.25199692e-01,  1.92760255e-01]],

       [[ 3.46495013e-01, -1.06178027e+00, -3.51175677e+00],
        [ 2.93162197e-03, -9.27254946e-02,  4.38643721e-01],
        [-5.82157104e-01, -1.04885239e-01,  1.14324537e+00],
        [ 1.01534526e+00,  9.65480232e-01, -6.84228466e-01],
        [-5.07418286e-01,  7.96788326e-01,  1.20186049e+00]],

       [[ 7.20673716e-01, -8.29432991e-01,  1.04052934e+00],
        [-6.59275162e-01,  5.50019316e-01,  1.04405925e+00],
        [-4.86850403e-01,  1.18065009e+00, -1.52629680e+00],
        [ 1.78136205e+00, -6.51149616e-01,  1.60402527e-01],
        [ 6.36830563e-01,  1.57683721e+00,  6.47779669e-01]],

       [[ 2.87804554e-01,  1.61080890e-01, -1.83120376e+00],
        [ 2.270942

In [107]:
# randint(): creates ndarray through random sampling between certain numbers
np.random.randint(1,100,size=(5,))

array([70, 19, 22, 68, 88])

In [108]:
np.random.randint(1,100,size=(5,2))

array([[77, 25],
       [82, 21],
       [74, 32],
       [17, 44],
       [37, 35]])

In [113]:
# seed():  Used to create random number in an equal way
#       :  keeps the same randome number 
np.random.seed(20)
np.random.randn(3,4)


array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088]])

In [114]:
# choice(): random sampling from given 1d array
# If an integer is given > np.arrange(num) 
x=np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,size=(2,2))

array([[3. , 2. ],
       [1.5, 3. ]])

In [115]:
x=np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,size=(2,2),replace=False)

array([[2.6, 1. ],
       [3. , 2. ]])

In [116]:
np.random.choice(100, size=(3,4))

array([[32, 10,  6, 75],
       [18,  3, 77, 17],
       [43, 16, 18, 79]])

In [117]:
# Creating nd array using Probability distribution
# uniform()
np.random.uniform(1.0,3.0,size=(4,5))

array([[2.30157183, 1.53759048, 1.13464933, 2.54289028, 1.96196826],
       [1.65841282, 2.02128211, 1.52725766, 1.6210231 , 2.25370688],
       [2.11489962, 1.63715912, 1.78968644, 1.51594917, 2.16448225],
       [1.32325742, 2.19626764, 2.65164715, 1.31278344, 2.46860104]])

In [118]:
# normal()
np.random.normal(size=(3,4))


array([[ 1.38811608, -0.45503777,  0.58238365,  0.61882265],
       [ 1.72222527,  0.96625817, -0.95450949,  1.88129696],
       [ 0.35041236,  3.77989075,  1.29957816,  0.56336994]])

In [122]:
# Altering ndarray shape (additional to reshape()method)
# ravel(): alter multidimensional array into one dimensional array
# original data could be changed
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [124]:
np.ravel(x) # Back to one dimensional array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
np.ravel(x,order='F') #field first

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [131]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [133]:
temp=x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [134]:
temp[0]=100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [128]:
# flatten(): alter multidimensional array into one dimensional array
# creates a copy of the data, original data could be kept 
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
t= y.flatten(order="F")
t

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [132]:
t[0]=100
print(t)
print(y) # different from ravel, flatten() keeps the original data

[100   5  10   1   6  11   2   7  12   3   8  13   4   9  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Numpy Documentation
- [Numpy Official Document Link](https://www.numpy.org/devdocs/reference/)
- The best way to study modules with great examples is THE OFFICIAL DOCUMENT
