<a href="https://colab.research.google.com/github/smileone22/20Fall_R-BASIC-learningforBigData/blob/master/3_Numpy_Modules_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##1. Sorting 1-D array




In [ ]:
arr =np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
np.sort(arr) # sorted in ascending order 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
# To sort in descending order, have -1 for option value
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr # The original data set does not get altered
# In order to save the sorted array, array should be sorted  

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
arr2 = np.sort(arr) # put returned sorted array to the variable
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 2. Sorting N-dimensional array 

In [ ]:
arr2d =np.array([[5,6,7,8],[4,3,2,1],[10,9,12,11]])
arr2d, arr2d.shape

(array([[ 5,  6,  7,  8],
        [ 4,  3,  2,  1],
        [10,  9, 12, 11]]), (3, 4))

## 2-1. Sorting Columns ( from left to right)

In [ ]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## 2-2. Sorting Columns ( from top to bottom)

In [ ]:
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

##3. Returning sorted indexes through argsort

In [ ]:
# returns sorted indexes rather than sorted values
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [ ]:
np.argsort(arr2d,axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

## 4-1. Matrices - Addition 

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[1,2,3]])

In [ ]:
a+b

array([[4, 6, 8],
       [5, 7, 9]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])

In [ ]:
a+b # In order to add matrices, its dimensions should match 

ValueError: ignored

##4-2. Matrices - Subtraction

In [ ]:
# Subtraction


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[1,2,3]])

In [ ]:
a-b

array([[-2, -2, -2],
       [ 3,  3,  3]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])

In [ ]:
a-b # error 

ValueError: ignored

##4-3. Matrices - Multiplication

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[1,2,3]])

In [ ]:
# This is regular multiplication but there is also "dot product"
a*b

array([[ 3,  8, 15],
       [ 4, 10, 18]])

In [ ]:
# Dot Product
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[1,2,3]])
a.shape, b.shape # 3 != 2 

((2, 3), (2, 3))

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
a.shape, b.shape # 3=3 

((2, 3), (3, 2))

In [ ]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [ ]:
a.dot(b) # another way to compute dot product 

array([[22, 28],
       [49, 64]])

##4-4. Broadcasting

In [ ]:
a= np.array([[1,2,3],[2,3,4]])
b= np.array([[3,3,3],[3,3,3]])
a+b

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [ ]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [ ]:
a= np.array([[1,2,3],[2,3,4]])
b= np.array([[1],[2]])
a.shape, b.shape

((2, 3), (2, 1))

In [ ]:
# maintains the shape of the original array 
a*b

array([[1, 2, 3],
       [4, 6, 8]])